### ISSUE TITLE
Positioning not work

### ISSUE THREAD

**Issue by jsdussanc** [situmtech/situm-ios-getting-started#1]
If I only use the option to Positioning (start location button), it does not do anything at all, it stays in state 2 (not in build)

![imagen subida desde ios 1](https://user-images.githubusercontent.com/7362688/38389640-a96d24fe-38e4-11e8-91cd-f76bf60f66ea.png)

**Comment by jsdussanc** [comment]
Plan of my building:
![planesteet](https://user-images.githubusercontent.com/7362688/38390152-0d5107e6-38e6-11e8-98eb-2aebb936d0d1.png)

Calibration of my building:
![planesteet_calibracion](https://user-images.githubusercontent.com/7362688/38390157-10099db8-38e6-11e8-82b0-17ed5c8d7a0d.png)

**Comment by CrisBarreiro** [comment]
Please note this repository has been discontinued, therefore we are no longer providing support for it. Check [Situm iOS code samples](https://github.com/situmtech/situm-ios-code-samples) instead
